<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Akshay" failures="1" tests="6" name="com.TutorialNinja.TestCases.Login" time="33.928" errors="0" timestamp="2024-07-16T20:49:35 IST" skipped="0">
  <testcase classname="com.TutorialNinja.TestCases.Login" name="varifyLoginWithValidCerdentils" time="5.517"/>
  <system-out/>
  <testcase classname="com.TutorialNinja.TestCases.Login" name="varifyLoginWithValidCerdentils" time="6.686"/>
  <system-out/>
  <testcase classname="com.TutorialNinja.TestCases.Login" name="varifyLoginWithInvalidCredentils" time="7.095"/>
  <system-out/>
  <testcase classname="com.TutorialNinja.TestCases.Login" name="varifyLoginWithInvalidEmailAndValidPasswordCredentils" time="6.263"/>
  <system-out/>
  <testcase classname="com.TutorialNinja.TestCases.Login" name="varifyLoginWithValidEmailAndInValidPasswordCredentils" time="4.597"/>
  <system-out/>
  <testcase classname="com.TutorialNinja.TestCases.Login" name="varifyLoginWithoutProvidingAnyCredentils" time="3.770">
    <failure message="Warning Message is not shown expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Warning Message is not shown expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.TutorialNinja.TestCases.Login.varifyLoginWithoutProvidingAnyCredentils(Login.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- varifyLoginWithoutProvidingAnyCredentils -->
  <system-out/>
</testsuite> <!-- com.TutorialNinja.TestCases.Login -->
